name: Deploy render

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Set up Git (global context for runner)
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

    - name: Clone destination repo outside current dir
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: |
        echo "Creating directory ../destination"
        mkdir ../destination 
        echo "Cloning gabrielspirlan/petdex into ../destination"
        git clone https://x-access-token:${TARGET_REPO_TOKEN}@github.com/gabrielspirlan/petdex.git ../destination

    - name: Sync files from source to destination's working tree
      run: |
        
        echo "Optional: Backing up original content of destination repo (../destination)..."
        mkdir -p $GITHUB_WORKSPACE/destination_backup
        rsync -a --exclude='.git/' ../destination/ $GITHUB_WORKSPACE/destination_backup/

        echo "Syncing files from source ($GITHUB_WORKSPACE) to destination's working tree (../destination)..."
        rsync -av --delete --exclude='.git/' --exclude='destination_backup/' --exclude='.github/' $GITHUB_WORKSPACE/ ../destination/

    - name: Commit and push to destination
      run: |
        echo "Changing directory to ../destination"
        cd ../destination
        
        echo "Setting up Git identity for commit in destination repo..."
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        echo "Staging changes in destination repo..."
        git add .
        
        echo "Checking for changes to commit..."
        if git diff --staged --quiet; then
          echo "No changes to commit to the destination repository."
        else
          echo "Committing changes..."
          git commit -m "Sync: Update content from source ${{ github.repository }}@${{ github.sha }}"
          
          echo "Pushing changes to origin main of destination repo..."
          git push origin main
        fi
